In [1]:
from surprise import KNNBasic, SVD, SVDpp, NMF
from surprise import Dataset
from surprise.model_selection import cross_validate

In [3]:
data = Dataset.load_builtin('ml-100k',prompt=False)

In [4]:
model = KNNBasic()
cross_validate(model,data,measures=['rmse','mae'],cv=5,n_jobs=4, verbose=True) #MAE 방식 => 오차 절댓값의 평균, rmse=>오차 제곱의 평균

Evaluating RMSE, MAE of algorithm KNNBasic on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9743  0.9856  0.9821  0.9759  0.9765  0.9789  0.0043  
MAE (testset)     0.7667  0.7769  0.7775  0.7732  0.7700  0.7729  0.0041  
Fit time          0.54    0.56    0.59    0.50    0.41    0.52    0.06    
Test time         2.74    2.77    2.73    2.80    1.84    2.58    0.37    


{'test_rmse': array([0.97428571, 0.98563795, 0.98212817, 0.97587781, 0.97646681]),
 'test_mae': array([0.76672589, 0.77690505, 0.77754588, 0.77315697, 0.77004413]),
 'fit_time': (0.5427513122558594,
  0.5561563968658447,
  0.5944232940673828,
  0.4958794116973877,
  0.40613889694213867),
 'test_time': (2.7355384826660156,
  2.769327163696289,
  2.7281248569488525,
  2.8000528812408447,
  1.8438465595245361)}

In [5]:
model = SVD()
cross_validate(model,data,measures=['rmse','mae'],cv=5,n_jobs=4, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9343  0.9367  0.9302  0.9392  0.9404  0.9362  0.0036  
MAE (testset)     0.7357  0.7362  0.7356  0.7413  0.7407  0.7379  0.0025  
Fit time          2.00    2.07    2.05    1.96    1.58    1.93    0.18    
Test time         0.42    0.46    0.49    0.46    0.34    0.43    0.05    


{'test_rmse': array([0.93432352, 0.93674927, 0.93024403, 0.9392273 , 0.94041727]),
 'test_mae': array([0.73571976, 0.73622395, 0.73557666, 0.74125281, 0.74074761]),
 'fit_time': (2.0034470558166504,
  2.0683043003082275,
  2.0451972484588623,
  1.960634469985962,
  1.5801100730895996),
 'test_time': (0.42157506942749023,
  0.4622609615325928,
  0.48775529861450195,
  0.45566725730895996,
  0.34079456329345703)}

In [6]:
model = NMF()#음수 미포함 행렬 분해
cross_validate(model,data,measures=['rmse','mae'],cv=5,n_jobs=4, verbose=True)

Evaluating RMSE, MAE of algorithm NMF on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9666  0.9707  0.9568  0.9641  0.9609  0.9638  0.0048  
MAE (testset)     0.7605  0.7616  0.7537  0.7580  0.7564  0.7580  0.0028  
Fit time          2.64    2.82    2.82    2.87    2.05    2.64    0.31    
Test time         0.41    0.50    0.35    0.32    0.30    0.37    0.07    


{'test_rmse': array([0.96664512, 0.9707286 , 0.95676104, 0.96407296, 0.96093128]),
 'test_mae': array([0.76051183, 0.76157128, 0.7537178 , 0.75804821, 0.75635045]),
 'fit_time': (2.6380879878997803,
  2.815760374069214,
  2.8217859268188477,
  2.8747763633728027,
  2.049285888671875),
 'test_time': (0.4059436321258545,
  0.5038657188415527,
  0.34634828567504883,
  0.31717419624328613,
  0.30109429359436035)}

In [8]:
model = SVDpp()
cross_validate(model,data,measures=['rmse','mae'],cv=5,n_jobs=4, verbose=True)

Evaluating RMSE, MAE of algorithm SVDpp on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9194  0.9240  0.9219  0.9166  0.9246  0.9213  0.0030  
MAE (testset)     0.7219  0.7251  0.7219  0.7212  0.7250  0.7230  0.0017  
Fit time          49.08   48.47   48.03   48.33   36.55   46.09   4.78    
Test time         9.36    9.24    9.54    9.31    7.38    8.97    0.80    


{'test_rmse': array([0.91941601, 0.92395641, 0.92192326, 0.91661616, 0.92464482]),
 'test_mae': array([0.72188492, 0.72509244, 0.72186078, 0.7211524 , 0.72495968]),
 'fit_time': (49.08102250099182,
  48.47411799430847,
  48.028878688812256,
  48.332727909088135,
  36.54990911483765),
 'test_time': (9.357846736907959,
  9.244680643081665,
  9.54280686378479,
  9.314441680908203,
  7.383686304092407)}

#하이브리드 

In [9]:
import numpy as np
from sklearn.decomposition import randomized_svd,non_negative_factorization
from surprise import Dataset

In [15]:
data =  Dataset.load_builtin('ml-100k',prompt=False)
raw_data = np.array(data.raw_ratings,dtype=int)
raw_data[:,0] -= 1
raw_data[:,1] -= 1

In [16]:
n_users = np.max(raw_data[:,0])
n_movies = np.max(raw_data[:,1])
shape = (n_users+1,n_movies+1)
shape

(943, 1682)

In [17]:
adj_matrix = np.ndarray(shape, dtype=int)
for user_id,movie_id,rating,time in raw_data:
    adj_matrix[user_id][movie_id] = rating

In [18]:
adj_matrix

array([[5, 3, 4, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 5, 0, ..., 0, 0, 0]])

In [19]:
U, S, V = randomized_svd(adj_matrix, n_components=2)
S = np.diag(S)

C:\Users\won\anaconda3\lib\site-packages\sklearn\utils\extmath.py:370: FutureWarning: If 'random_state' is not supplied, the current default is to use 0 as a fixed seed. This will change to  None in version 1.2 leading to non-deterministic results that better reflect nature of the randomized_svd solver. If you want to silence this warning, set 'random_state' to an integer seed or to None explicitly depending if you want your code to be deterministic or not.
  warnings.warn(


In [20]:
print(U.shape)
print(S.shape)
print(V.shape)

(943, 2)
(2, 2)
(2, 1682)


In [24]:
U

array([[ 0.06580431,  0.00597507],
       [ 0.01402104, -0.04662601],
       [ 0.00565798, -0.02561846],
       ...,
       [ 0.00744452, -0.02502129],
       [ 0.02403119,  0.0080961 ],
       [ 0.04224209, -0.01092715]])

In [22]:
def compute_cos_similarity(v1,v2):
    norm1 = np.sqrt(np.sum(np.square(v1)))
    norm2 = np.sqrt(np.sum(np.square(v2)))#sqrt = 루트,square=제곱
    dot = np.dot(v1,v2)
    return dot/(norm1*norm2)

In [25]:
#사용자 기반 추천
my_id, my_vector = 0, U[0]
best_match, best_match_id, best_match_vector =-1,-1,[]

for user_id, user_vector in enumerate(U):
    if my_id != user_id:
        cos_similarity = compute_cos_similarity(my_vector,user_vector)
        if cos_similarity > best_match:
            best_match = cos_similarity
            best_match_id = user_id
            best_match_vector = user_vector
            
print("Best Match:{}, Best Match ID:{}".format(best_match, best_match_id))

Best Match:0.9999942295956322, Best Match ID:235


In [26]:
#915번은 봤지만 나는 안 본 영화 추천
recommend_list=[]
for i,log in enumerate(zip(adj_matrix[my_id], adj_matrix[best_match_id])):
    log1,log2 = log
    if log1<1 and log2>0.:
        recommend_list.append(i)
print(recommend_list)

[272, 273, 274, 281, 285, 288, 293, 297, 303, 306, 312, 317, 327, 332, 369, 410, 418, 419, 422, 426, 428, 431, 434, 442, 461, 475, 477, 482, 495, 503, 504, 505, 506, 509, 519, 520, 522, 525, 531, 545, 548, 590, 594, 595, 613, 631, 654, 658, 660, 672, 684, 685, 691, 695, 698, 704, 716, 728, 734, 749, 755, 863, 865, 933, 1012, 1038, 1101, 1327, 1400]


In [34]:
#사물기반 추천
my_id, my_vector = 0, V.T[0]
best_match, best_match_id, best_match_vector =-1,-1,[]

for user_id, user_vector in enumerate(V.T):
    if my_id != user_id:
        cos_similarity = compute_cos_similarity(my_vector,user_vector)
        if cos_similarity > best_match:
            best_match = cos_similarity
            best_match_id = user_id
            best_match_vector = user_vector
            
print("Best Match:{}, Best Match ID:{}".format(best_match, best_match_id))

Best Match:0.9999999951364141, Best Match ID:1287


In [35]:
recommend_list=[]
for i,user_vector in enumerate(adj_matrix):
    
    if adj_matrix[i][my_id]>0.9:
        recommend_list.append(i)
print(recommend_list)

[0, 1, 4, 5, 9, 12, 14, 15, 16, 17, 19, 20, 22, 24, 25, 37, 40, 41, 42, 43, 44, 48, 53, 55, 56, 57, 58, 61, 62, 63, 64, 65, 66, 69, 71, 72, 74, 76, 78, 80, 81, 82, 83, 88, 91, 92, 93, 94, 95, 96, 98, 100, 101, 105, 107, 108, 116, 119, 120, 123, 124, 127, 129, 130, 133, 136, 137, 140, 143, 144, 147, 149, 150, 156, 157, 159, 161, 167, 173, 176, 177, 180, 181, 183, 188, 192, 193, 197, 198, 199, 200, 201, 202, 203, 208, 209, 212, 215, 221, 222, 229, 230, 231, 233, 234, 241, 242, 243, 245, 246, 247, 248, 249, 250, 251, 252, 253, 255, 261, 262, 264, 267, 270, 273, 274, 275, 276, 278, 279, 285, 286, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 300, 302, 304, 306, 307, 310, 311, 312, 313, 319, 321, 323, 324, 325, 326, 329, 330, 331, 335, 337, 338, 339, 342, 343, 344, 346, 347, 349, 356, 358, 359, 362, 364, 370, 373, 377, 378, 379, 380, 386, 387, 388, 389, 392, 393, 394, 395, 397, 398, 400, 401, 402, 405, 406, 410, 411, 415, 416, 418, 421, 423, 424, 428, 431, 433, 434, 437, 440, 444, 

In [29]:
A,B,iter = non_negative_factorization(adj_matrix,n_components=2)

In [30]:
np.matmul(A,B)

array([[3.71107433e+00, 1.48461856e+00, 7.39541570e-01, ...,
        3.64501983e-03, 1.45513751e-02, 1.44116215e-02],
       [2.11729713e+00, 2.37145679e-01, 5.51637757e-01, ...,
        4.76290749e-03, 2.84605930e-05, 0.00000000e+00],
       [9.85325089e-01, 1.10360320e-01, 2.56715279e-01, ...,
        2.21651094e-03, 1.32446863e-05, 0.00000000e+00],
       ...,
       [1.04478344e+00, 1.17019891e-01, 2.72206478e-01, ...,
        2.35026384e-03, 1.40439223e-05, 0.00000000e+00],
       [1.45769331e+00, 5.42108391e-01, 2.99217251e-01, ...,
        1.61232500e-03, 5.15892655e-03, 5.10748255e-03],
       [2.44709957e+00, 9.41278705e-01, 4.95671746e-01, ...,
        2.56934867e-03, 9.08400301e-03, 8.99501717e-03]])

In [31]:
#사용자 기반 추천
my_id, my_vector = 0, U[0]
best_match, best_match_id, best_match_vector =-1,-1,[]

for user_id, user_vector in enumerate(U):
    if my_id != user_id:
        cos_similarity = compute_cos_similarity(my_vector,user_vector)
        if cos_similarity > best_match:
            best_match = cos_similarity
            best_match_id = user_id
            best_match_vector = user_vector
            
print("Best Match:{}, Best Match ID:{}".format(best_match, best_match_id))

Best Match:0.9999942295956322, Best Match ID:235


In [32]:
recommend_list=[]
for i,log in enumerate(zip(adj_matrix[my_id], adj_matrix[best_match_id])):
    log1,log2 = log
    if log1<1 and log2>0.:
        recommend_list.append(i)
print(recommend_list)

[272, 273, 274, 281, 285, 288, 293, 297, 303, 306, 312, 317, 327, 332, 369, 410, 418, 419, 422, 426, 428, 431, 434, 442, 461, 475, 477, 482, 495, 503, 504, 505, 506, 509, 519, 520, 522, 525, 531, 545, 548, 590, 594, 595, 613, 631, 654, 658, 660, 672, 684, 685, 691, 695, 698, 704, 716, 728, 734, 749, 755, 863, 865, 933, 1012, 1038, 1101, 1327, 1400]


In [33]:
#사용자 기반 추천
my_id, my_vector = 0, V.T[0]
best_match, best_match_id, best_match_vector =-1,-1,[]

for user_id, user_vector in enumerate(V.T):
    if my_id != user_id:
        cos_similarity = compute_cos_similarity(my_vector,user_vector)
        if cos_similarity > best_match:
            best_match = cos_similarity
            best_match_id = user_id
            best_match_vector = user_vector
            
print("Best Match:{}, Best Match ID:{}".format(best_match, best_match_id))

Best Match:0.9999999758529563, Best Match ID:873


In [ ]:
recommend_list=[]
for i,log in enumerate(zip(adj_matrix[my_id], adj_matrix[best_match_id])):
    log1,log2 = log
    if log1<1 and log2>0.:
        recommend_list.append(i)
print(recommend_list)